POST http://localhost:3000/tasks
Content-Type: application/json

{
  "title": "GRRfaAArGGHg",
  "description": "Lugurk"
}

###
GET http://localhost:3000/tasks/7e98c48c-f01f-42ae-838d-c1428e6f1a6b
Authorization: Bearer {{auth_token}}


###
GET http://localhost:3000/tasks
Authorization: Bearer {{auth_token}}

###
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "username": "bilbo_bigguns",
  "password": "P@ssw0rd"
}

###
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "username": "bilbo_bigguns",
  "password": "P@ssw0rd"
}
> {%
  client.test('request success', () => {
    const expected = 200;
    client.assert(response.status === expected, `incorrect response: expected ${expected}, recv'd ${response.status}`);
  });

  client.test('response is json', () => {
    client.assert(response.contentType.mimeType.includes('application/json'), "response is not json");
  });

  client.test('has a body', () => {
    client.assert(!!response.body, "response have no body");
  });

  client.test('has a json object body', () => {
    client.assert(!!response.body.accessToken, "response have no tokken");
  });

  // client.log(JSON.stringify(response.body));

  client.global.set("auth_token", response.body.accessToken);
 %}

###
POST http://localhost:3000/tasks
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "title": "maken magic",
  "description": "yo frip this ya hippies"
}


### Authorization by token, part 2. Use token to authorize.
GET https://httpbin.org/headers
Authorization: Bearer {{auth_token}}


### eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJpbGJvX2JpZ2d1bnMiLCJpYXQiOjE2NjQyMTA2NTgsImV4cCI6MTY2NDIxNDI1OH0.Lf_-SHTB_nIteZ67Qk-fWtIRrEnuKvW9Em63Kj8ugK






